### ISSUE TITLE
Error while installing dogehouse wrapper

### ISSUE THREAD

**Issue by ycl310** [Arthurdw/dogehouse.py#3]
```
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\my_name\dogehousebot\env\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\my_name\\AppData\\Local\\Temp\\pip-install-303pxob6\\dogehouse\\setup.py'"'"'; __file__='"'"'C:\\Users\\my_name\\AppData\\Local\\Temp\\pip-install-303pxob6\\dogehouse\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\yc_la\AppData\Local\Temp\pip-pip-egg-info-qg1y2p5l'
         cwd: C:\Users\my_name\AppData\Local\Temp\pip-install-303pxob6\dogehouse\
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Usersmy_name\AppData\Local\Temp\pip-install-303pxob6\dogehouse\setup.py", line 3, in <module>
        from dogehouse import __version__
      File "C:\Users\my_name\AppData\Local\Temp\pip-install-303pxob6\dogehouse\dogehouse\__init__.py", line 24, in <module>
        from .client import DogeClient, event, command
      File "C:\Users\my_name\AppData\Local\Temp\pip-install-303pxob6\dogehouse\dogehouse\client.py", line 34, in <module>
        from .entities import User, Room, UserPreview, Message
      File "C:\Users\my_name\AppData\Local\Temp\pip-install-303pxob6\dogehouse\dogehouse\entities.py", line 27, in <module>
        from dateutil.parser import isoparse
    ModuleNotFoundError: No module named 'dateutil'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by xkral-tr** [comment]
same @Arthurdw please help

**Comment by Arthurdw** [comment]
`pip install -U python-dateutil`
